spring:
  mail:
    host: smtp.163.com # Sending mail server
    username: ENC(bDoly3etf13m443PORHr9Xs2rcfgmw6UlfU6Di9E810Uh8Tq8Vey5NROPTzkoF0OCcqkuilshPnZ8265CdKvqA==) # Email address for sending emails
    password: ENC(Aid4dayAgpvTHTlBJxTcyw7BKLKPR1vdMX/k4LNCkJ+e1Lu1tPQu2YTdYoBas5ePY9UeCnpeOjibEiOBGh46rQ==) # Client authorization code
    properties.mail.smtp.port: 994 # 465 or 994
    nickname: 花卷买卖
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

sms:
  aliyun:
    accessKeyID: ENC(Pi0XBxmVDiBcc4dAPWFTihkNSuoAPKj3MIEyGhk2wgDuN7Q2es+PL/skEU2SBhOzhnANYqjg+BmCkDg4Yb2xEw==) # accessKeyID
    accessKeySecret: ENC(13Lt+OVG7CBiLshYIZ0+N/8iwqXxRCheIJlj/tZfKvq3R2SfHCJ4Mdduo4xsklCSWfBEyqjveee7zqAwTnyK+g==) # accessKeySecret
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    templateCode: SMS_205882311 # your template code
    signName: 花卷买卖 # your signature

oss:
  bucketName: ENC(4ZScEvDKzE0ihJ6Xtl+ooY5ZSDJuETOvGtw99EkdXaqmaNaZelZSL7y49PLL2gJU)
  accessKeyId: ENC(49/8egPEY/BQdE9BowtJgGQHnfZoSF8x2AeJ1IOX7vi97woIVEd1Iwjd1wfkmsxIvAgWFLNl+yPp4QI+RHTldA==)
  accessKeySecret: ENC(qhNzocskPBA060OHu7g7mHnJHzv75hMldZ2ILr3vV+yX55ptjT3gkPOuPUiYX9Oa8JuRq6D4KQ5zn7/yqEAqKw==)
  # OSS region
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucket: https://spring-oss.oss-cn-beijing.aliyuncs.com
  fileHost: images